In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('estimated_numbers.csv')

In [3]:
pd.set_option('display.max_column',data.shape[1])
data

,Country,Year,No. of cases,No. of deaths,No. of cases_median,No. of cases_min,No. of cases_max,No. of deaths_median,No. of deaths_min,No. of deaths_max,WHO Region
0,Afghanistan,2017,630308[495000-801000],298[110-510],630308,495000.0,801000.0,298,110.0,510.0,Eastern Mediterranean
1,Algeria,2017,0,0,0,NaN,NaN,0,NaN,NaN,Africa
2,Angola,2017,4615605[3106000-6661000],13316[9970-16600],4615605,3106000.0,6661000.0,13316,9970.0,16600.0,Africa
3,Argentina,2017,0,0,0,NaN,NaN,0,NaN,NaN,Americas
4,Armenia,2017,0,0,0,NaN,NaN,0,NaN,NaN,Europe
...,...,...,...,...,...,...,...,...,...,...,...
851,Venezuela (Bolivarian Republic of),2010,57257[47000-74000],52[9-90],57257,47000.0,74000.0,52,9.0,90.0,Americas
852,Viet Nam,2010,23062[21000-26000],45[2-80],23062,21000.0,26000.0,45,2.0,80.0,Western Pacific
853,Yemen,2010,1134927[611000-2686000],2874[90-8490],1134927,611000.0,2686000.0,2874,90.0,8490.0,Eastern Mediterranean
854,Zambia,2010,2169307[1449000-3095000],6544[5580-7510],2169307,1449000.0,3095000.0,6544,5580.0,7510.0,Africa
855,Zimbabwe,2010,1095083[606000-1717000],2803[80-6190],1095083,606000.0,1717000.0,2803,80.0,6190.0,Africa

In [6]:
data.Country.value_counts()

Malaysia       8
Gabon          8
Afghanistan    8
Benin          8
Ecuador        8
              ..
Guyana         8
Liberia        8
Cabo Verde     8
Brazil         8
Uganda         8
Name: Country, Length: 107, dtype: int64

In [10]:
pd.unique(data.Country)

array(['Afghanistan', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Azerbaijan', 'Bangladesh', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Botswana', 'Brazil',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Central African Republic', 'Chad', 'China', 'Colombia', 'Comoros',
       'Congo', 'Costa Rica', "Côte d'Ivoire",
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'India',
       'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Kazakhstan',
       'Kenya', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Liberia', 'Madagascar', 'Malawi', 'Malaysia', 'Mali',
       'Mauritania', 'Mexico', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Nicaragua', 'Niger', 'Nigeria', 'Oman',
       'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Republic of Korea', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Sierra Leone',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Sri Lanka', 'Sudan', 'Suriname', 'Syrian Arab Republic',
       'Tajikistan', 'Thailand', 'Timor-Leste', 'Togo', 'Turkey',
       'Turkmenistan', 'Uganda', 'United Arab Emirates',
       'United Republic of Tanzania', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [13]:
data[data.iloc[:,0]=='Chad']

,Country,Year,No. of cases,No. of deaths,No. of cases_median,No. of cases_min,No. of cases_max,No. of deaths_median,No. of deaths_min,No. of deaths_max,WHO Region
19,Chad,2017,2779489[1449000-4832000],8729[6640-10800],2779489,1449000.0,4832000.0,8729,6640.0,10800.0,Africa
126,Chad,2016,2689908[1404000-4670000],8900[6730-11100],2689908,1404000.0,4670000.0,8900,6730.0,11100.0,Africa
233,Chad,2015,2690084[1407000-4633000],9206[6950-11500],2690084,1407000.0,4633000.0,9206,6950.0,11500.0,Africa
340,Chad,2014,2797275[1513000-4737000],9749[7350-12200],2797275,1513000.0,4737000.0,9749,7350.0,12200.0,Africa
447,Chad,2013,2947833[1699000-4685000],10632[8000-13300],2947833,1699000.0,4685000.0,10632,8000.0,13300.0,Africa
554,Chad,2012,3296088[2209000-4858000],11575[8700-14400],3296088,2209000.0,4858000.0,11575,8700.0,14400.0,Africa
661,Chad,2011,3565593[2570000-4807000],12809[9660-16000],3565593,2570000.0,4807000.0,12809,9660.0,16000.0,Africa
768,Chad,2010,3594883[2594000-4735000],13695[10300-17000],3594883,2594000.0,4735000.0,13695,10300.0,17000.0,Africa

In [15]:
data.dtypes

Country                  object
Year                      int64
No. of cases             object
No. of deaths            object
No. of cases_median       int64
No. of cases_min        float64
No. of cases_max        float64
No. of deaths_median      int64
No. of deaths_min       float64
No. of deaths_max       float64
WHO Region               object
dtype: object

In [19]:
data.isna().sum(axis=0)

Country                   0
Year                      0
No. of cases              0
No. of deaths             0
No. of cases_median       0
No. of cases_min        312
No. of cases_max        312
No. of deaths_median      0
No. of deaths_min       332
No. of deaths_max       332
WHO Region                0
dtype: int64

In [20]:
data.isnull().sum(axis=0)#les deux sont equivalent

Country                   0
Year                      0
No. of cases              0
No. of deaths             0
No. of cases_median       0
No. of cases_min        312
No. of cases_max        312
No. of deaths_median      0
No. of deaths_min       332
No. of deaths_max       332
WHO Region                0
dtype: int64

In [34]:
#data['No. of deaths_max'].sort_values(ascending=False)

data.sort_values(by=['No. of deaths_max'],ascending=False) #permet de trier les valeurs aberantent dans No

,Country,Year,No. of cases,No. of deaths,No. of cases_median,No. of cases_min,No. of cases_max,No. of deaths_median,No. of deaths_min,No. of deaths_max,WHO Region
818,Nigeria,2010,60749349[43800000-83240000],146734[115000-179000],60749349,43800000.0,83240000.0,146734,115000.0,179000.0,Africa
711,Nigeria,2011,60529456[43880000-82700000],136533[107000-166000],60529456,43880000.0,82700000.0,136533,107000.0,166000.0,Africa
604,Nigeria,2012,61587135[43510000-83800000],125290[98100-152000],61587135,43510000.0,83800000.0,125290,98100.0,152000.0,Africa
497,Nigeria,2013,62020888[43310000-84840000],116472[91200-142000],62020888,43310000.0,84840000.0,116472,91200.0,142000.0,Africa
390,Nigeria,2014,59365039[41180000-81580000],107843[84600-131000],59365039,41180000.0,81580000.0,107843,84600.0,131000.0,Africa
...,...,...,...,...,...,...,...,...,...,...,...
841,Thailand,2010,32480,80,32480,NaN,NaN,80,NaN,NaN,South-East Asia
844,Turkey,2010,0,0,0,NaN,NaN,0,NaN,NaN,Europe
845,Turkmenistan,2010,0,0,0,NaN,NaN,0,NaN,NaN,Europe
847,United Arab Emirates,2010,0,0,0,NaN,NaN,0,NaN,NaN,Eastern Mediterranean
849,Uzbekistan,2010,3,0,3,NaN,NaN,0,NaN,NaN,Europe

In [36]:
data.drop(axis=1,index=[818,711])

,Country,Year,No. of cases,No. of deaths,No. of cases_median,No. of cases_min,No. of cases_max,No. of deaths_median,No. of deaths_min,No. of deaths_max,WHO Region
0,Afghanistan,2017,630308[495000-801000],298[110-510],630308,495000.0,801000.0,298,110.0,510.0,Eastern Mediterranean
1,Algeria,2017,0,0,0,NaN,NaN,0,NaN,NaN,Africa
2,Angola,2017,4615605[3106000-6661000],13316[9970-16600],4615605,3106000.0,6661000.0,13316,9970.0,16600.0,Africa
3,Argentina,2017,0,0,0,NaN,NaN,0,NaN,NaN,Americas
4,Armenia,2017,0,0,0,NaN,NaN,0,NaN,NaN,Europe
...,...,...,...,...,...,...,...,...,...,...,...
851,Venezuela (Bolivarian Republic of),2010,57257[47000-74000],52[9-90],57257,47000.0,74000.0,52,9.0,90.0,Americas
852,Viet Nam,2010,23062[21000-26000],45[2-80],23062,21000.0,26000.0,45,2.0,80.0,Western Pacific
853,Yemen,2010,1134927[611000-2686000],2874[90-8490],1134927,611000.0,2686000.0,2874,90.0,8490.0,Eastern Mediterranean
854,Zambia,2010,2169307[1449000-3095000],6544[5580-7510],2169307,1449000.0,3095000.0,6544,5580.0,7510.0,Africa
855,Zimbabwe,2010,1095083[606000-1717000],2803[80-6190],1095083,606000.0,1717000.0,2803,80.0,6190.0,Africa